/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.ceymikey.websocketj;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

public class Connector {
    public static void connect(String hostname) throws IOException {
        URL url = new URL("http://" + hostname);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        int responseCode = connection.getResponseCode();

        if (responseCode >= 200 && responseCode < 400) {
            System.out.println("Connection to " + hostname + " established (including redirects) | Protocol: https");
        } else {
            System.out.println("Connection to " + url + " failed | protocol error: " + responseCode);
            throw new IOException("Connection failed with non-success status code");
        }
    }
}
