/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.ceymikey.websocketj;

import java.io.IOException;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) throws IOException {
        Connector.connect("gradle.org");
    }
}
