/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.ceymikey.webutilsj;

import dev.ceymikey.webutilsj.utils.Jwu;

import java.io.IOException;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) throws IOException {
        Connector.connect("gradle.org");
        try {
            String url = "https://breezenodes.com/";
            String responseData = Jwu.fetch(url);
            System.out.println(responseData);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
